export const MOVIE_TYPES = {
  INTJ: {
    type: 'INTJ',
    nickname: '설계된 반전의 전략가',
    emoji: '🕶️',
    description:
      '복선 하나까지 계산하며 보는 타입. 치밀한 플롯과 지적인 반전이 있는 영화에서 희열을 느낍니다. 결말을 먼저 맞히고 뿌듯해하는 사람이 바로 당신.',
    genreIds: [878, 9648, 53],
    tvGenreIds: [10765, 9648, 80],
    bestMatch: 'ENFP',
    worstMatch: 'ESFP',
  },
  INTP: {
    type: 'INTP',
    nickname: '떡밥 채굴 분석가',
    emoji: '🔬',
    description:
      '영화가 끝나면 해석 영상과 위키를 정독하는 타입. 세계관이 촘촘한 SF와 미스터리에 빠지면 밤새는 줄 모릅니다.',
    genreIds: [878, 9648, 99],
    tvGenreIds: [10765, 9648, 99],
    bestMatch: 'ENTJ',
    worstMatch: 'ESFJ',
  },
  ENTJ: {
    type: 'ENTJ',
    nickname: '왕좌를 노리는 야심가',
    emoji: '👑',
    description:
      '주인공이 성장해 판을 뒤집는 서사에 심장이 뜁니다. 권력, 전략, 승부의 세계를 다룬 묵직한 영화가 당신의 취향.',
    genreIds: [80, 53, 36],
    tvGenreIds: [80, 10768, 9648],
    bestMatch: 'INTP',
    worstMatch: 'INFP',
  },
  ENTP: {
    type: 'ENTP',
    nickname: '클리셰 파괴 선동가',
    emoji: '⚡',
    description:
      '뻔한 전개는 거부합니다. 장르를 비트는 신선한 영화, 말맛 넘치는 대사, 도발적인 아이디어에 열광하는 타입.',
    genreIds: [35, 878, 80],
    tvGenreIds: [35, 10765, 80],
    bestMatch: 'INFJ',
    worstMatch: 'ISFJ',
  },
  INFJ: {
    type: 'INFJ',
    nickname: '새벽 감성 예언자',
    emoji: '🌙',
    description:
      '영화가 끝나도 며칠씩 여운에 잠기는 타입. 인간의 내면을 깊게 파고드는 드라마와 은유 가득한 판타지가 당신을 위한 영화.',
    genreIds: [18, 14, 9648],
    tvGenreIds: [18, 10765, 9648],
    bestMatch: 'ENTP',
    worstMatch: 'ESTP',
  },
  INFP: {
    type: 'INFP',
    nickname: '눈물샘 장인 몽상가',
    emoji: '🌸',
    description:
      '엔딩 크레딧이 올라가도 자리를 못 뜨는 타입. 잔잔하지만 마음을 울리는 이야기, 아름다운 영상미에 약합니다.',
    genreIds: [18, 10749, 16],
    tvGenreIds: [18, 10766, 16],
    bestMatch: 'ENTJ',
    worstMatch: 'ESTJ',
  },
  ENFJ: {
    type: 'ENFJ',
    nickname: '단체관람 주선자',
    emoji: '🎗️',
    description:
      '좋은 영화는 꼭 주변에 전파해야 직성이 풀리는 타입. 사람과 사람 사이의 유대, 성장과 연대의 이야기에 감동합니다.',
    genreIds: [18, 36, 10402],
    tvGenreIds: [18, 10751, 10766],
    bestMatch: 'ISFP',
    worstMatch: 'ISTP',
  },
  ENFP: {
    type: 'ENFP',
    nickname: '무지개빛 모험가',
    emoji: '🌈',
    description:
      '보고 싶은 영화가 항상 10개쯤 쌓여있는 타입. 상상력을 자극하는 모험과 유쾌한 로맨틱 코미디 사이를 자유롭게 오갑니다.',
    genreIds: [12, 14, 35],
    tvGenreIds: [10759, 10765, 35],
    bestMatch: 'INTJ',
    worstMatch: 'ISTJ',
  },
  ISTJ: {
    type: 'ISTJ',
    nickname: '고증 검수 원칙주의자',
    emoji: '📋',
    description:
      '개연성과 고증이 탄탄한 영화를 신뢰하는 타입. 실화 기반 드라마, 역사물, 정통 범죄물의 묵직함을 사랑합니다.',
    genreIds: [36, 80, 18],
    tvGenreIds: [80, 18, 10768],
    bestMatch: 'ESFP',
    worstMatch: 'ENFP',
  },
  ISFJ: {
    type: 'ISFJ',
    nickname: '포근한 인생영화 수집가',
    emoji: '🧸',
    description:
      '마음이 따뜻해지는 영화를 소중히 아껴보는 타입. 가족, 우정, 일상의 온기를 담은 이야기가 당신의 힐링 포인트.',
    genreIds: [10751, 18, 10749],
    tvGenreIds: [10751, 18, 10766],
    bestMatch: 'ESTP',
    worstMatch: 'ENTP',
  },
  ESTJ: {
    type: 'ESTJ',
    nickname: '검증된 명작 관리자',
    emoji: '🏆',
    description:
      '평점과 수상 이력을 확인하고 보는 타입. 검증된 명작, 시원한 액션, 명확한 권선징악 서사가 당신의 안정적인 선택.',
    genreIds: [28, 80, 36],
    tvGenreIds: [10759, 80, 10768],
    bestMatch: 'ISFP',
    worstMatch: 'INFP',
  },
  ESFJ: {
    type: 'ESFJ',
    nickname: '국민픽 분위기메이커',
    emoji: '🍿',
    description:
      '다 같이 웃고 우는 영화관의 분위기를 사랑하는 타입. 온 가족이 즐길 수 있는 대중적인 인기작이 항상 옳습니다.',
    genreIds: [35, 10751, 10749],
    tvGenreIds: [35, 10751, 10766],
    bestMatch: 'ISTP',
    worstMatch: 'INTP',
  },
  ISTP: {
    type: 'ISTP',
    nickname: '무표정 액션 감정가',
    emoji: '🔧',
    description:
      '말 없이 보다가 명장면에서만 "오" 한마디 하는 타입. 군더더기 없는 액션과 긴장감 넘치는 스릴러가 당신의 세계.',
    genreIds: [28, 53, 878],
    tvGenreIds: [10759, 80, 10765],
    bestMatch: 'ESFJ',
    worstMatch: 'ENFJ',
  },
  ISFP: {
    type: 'ISFP',
    nickname: '감성 미장센 큐레이터',
    emoji: '🎨',
    description:
      '스토리보다 한 장면의 색감과 음악에 마음을 뺏기는 타입. 영상미가 아름다운 영화와 음악 영화가 당신의 갤러리.',
    genreIds: [10402, 10749, 16],
    tvGenreIds: [16, 10766, 18],
    bestMatch: 'ENFJ',
    worstMatch: 'ESTJ',
  },
  ESTP: {
    type: 'ESTP',
    nickname: '아드레날린 중독 스턴트맨',
    emoji: '🏍️',
    description:
      '생각은 나중에, 일단 달리는 타입. 폭발하는 액션, 스피드, 아슬아슬한 승부가 없으면 눈이 감기는 당신.',
    genreIds: [28, 12, 53],
    tvGenreIds: [10759, 80, 10764],
    bestMatch: 'ISFJ',
    worstMatch: 'INFJ',
  },
  ESFP: {
    type: 'ESFP',
    nickname: '팝콘 파티 스타',
    emoji: '🎉',
    description:
      '영화는 곧 축제! 신나는 음악, 화려한 볼거리, 빵빵 터지는 웃음이 있으면 그걸로 충분한 타입.',
    genreIds: [35, 10402, 12],
    tvGenreIds: [35, 10764, 10759],
    bestMatch: 'ISTJ',
    worstMatch: 'INTJ',
  },
}

export const GENRE_NAMES = {
  28: '액션',
  12: '모험',
  16: '애니메이션',
  35: '코미디',
  80: '범죄',
  99: '다큐멘터리',
  18: '드라마',
  10751: '가족',
  14: '판타지',
  36: '역사',
  27: '공포',
  10402: '음악',
  9648: '미스터리',
  10749: '로맨스',
  878: 'SF',
  53: '스릴러',
  10752: '전쟁',
  37: '서부',
}

/** TMDB TV 장르 ID 참고: 영화 장르와 체계가 다르다(스릴러/공포/로맨스/역사 등이 없음) */
export const TV_GENRE_NAMES = {
  10759: '액션·어드벤처',
  16: '애니메이션',
  35: '코미디',
  80: '범죄',
  99: '다큐멘터리',
  18: '드라마',
  10751: '가족',
  10762: '키즈',
  9648: '미스터리',
  10763: '뉴스',
  10764: '리얼리티',
  10765: 'SF·판타지',
  10766: '연속극',
  10767: '토크쇼',
  10768: '전쟁·정치',
  37: '서부',
}
